from . import invoice_stock
from . import product
from . import invoice
from . import stockpicking
from . import invoice_history
from . import credit_limit
from . import rack_transfer
from . import partial_transfer
from . import res_partner
from . import account_invoice
from . import sale
from . import sale_discount_approval
